### ISSUE TITLE
Some issues using the Unix port

### ISSUE THREAD

**Issue by rguillon** [kevinkk525/pysmartnode#27]
Hello,

I'm having a couple of issues with the unix port (a freshly built one: MicroPython v1.14-113-ga9140ab09 on 2021-03-15; linux version):

[2021-03-15 09:32:26] [main] [error] Traceback (most recent call last):
  File "/home/renaud/.micropython/lib/uasyncio/core.py", line 176, in run_until_complete
  File "/home/renaud/pysmartnode/pysmartnode/main.py", line 86, in _resetReason
AttributeError: 'module' object has no attribute 'listdir'

[2021-03-15 09:32:26] [main] [error] Traceback (most recent call last):
  File "/home/renaud/.micropython/lib/uasyncio/core.py", line 176, in run_until_complete
  File "/home/renaud/pysmartnode/pysmartnode/networking/mqtt.py", line 165, in _connected_handler
AttributeError: 'module' object has no attribute 'name'

Both are pretty easy to workaround as I don't need those features but I would like to make sure I am using pysmartnode correcly. Is is expecting a previous version of Micropython or maybe a custom os library?

**Comment by kevinkk525** [comment]
Hi,

you need to install the module "os" as it is sadly not installed by default. You can use upip for that:
```
import upip
upip.install("micropython-os")
```

I should document that in the readme. Sorry.

**Comment by rguillon** [comment]
It works, thanks
